pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -B test'
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh '''
                NAME=$(mvn -B -q -DforceStdout help:evaluate -Dexpression=project.name)
                VERSION=$(mvn -B -q -DforceStdout help:evaluate -Dexpression=project.version)
                java -jar target/${NAME}-${VERSION}.jar
                '''
            }
        }
    }
}
