pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -version 3.8.7clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -version 3.8.7 test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
